
#
#spring.resources.static-locations=file:E:/images

# datasoure默认使用JDBC

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ioc_iot
    username: root
    password: 123456

spring:
    datasource:
      data:
        url: jdbc:mysql://localhost:3306/jims-his
        username: root
        password: 123456
   zipkin:
      base-url: http://localhost:7001
    sleuth:
      sampler:
        percentage: 1.0

mybatis:
  mapper-locations: classpath:mapper/*.xml






