spring:
   datasource:
      url: jdbc:mysql://localhost:3306/ioc_iot
      username: root
      password: 123456

spring:
    datasource:
      data:
        url: jdbc:mysql://localhost:3306/jims-his
        username: root
        password: 123456
mybatis:
  mapper-locations: classpath:mapper/*.xml






