mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-locations: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.bonc.ioc.sso.model

spring:
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.16.3.24:31169/ioc_omp?useUnicode=true&characterEncoding=utf-8
      username: ioccp_kf
      password: ioccp_kf






