spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://pig:gip6666@localhost:1025/eureka
    registry-fetch-interval-seconds: 10
#建议使用ng负载均衡
security:
  auth:
    server: http://localhost:3000
