spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://mcp:mcp@localhost:1025/eureka
    registry-fetch-interval-seconds: 10
#认证服务器地址
security:
  auth:
    server: http://localhost:3000
#建议使用ng负载均衡
security:
  auth:
    server: http://localhost:3000
#指明监控的服务
turbine:
    appconfig: mcp-auth
    aggregator:
          clusterConfig: default
    clusterNameExpression: new String("default")
feign:
    hystrix:
        enabled: true