spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://mcp:mcp@localhost:1025/eureka
    registry-fetch-interval-seconds: 10
#建议使用ng负载均衡
security:
  auth:
    server: http://localhost:3000
---
spring:
  rabbitmq:
    host: 172.16.17.130
    port: 15672
    username: guest
    password: guest
#需要关闭，不然刷新消息总线时会报401
management:
  security:
    enabled: false

spring:
   datasource:
      url: jdbc:mysql://localhost:3306/ioc_iot
      username: root
      password: 123456

spring:
    datasource:
      data:
        url: jdbc:mysql://localhost:3306/jims-his
        username: root
        password: 123456
   zipkin:
      base-url: http://localhost:7001
    sleuth:
      sampler:
        percentage: 1.0

mybatis:
  mapper-locations: classpath:mapper/*.xml






