
#
#spring.resources.static-locations=file:E:/images

# datasoure默认使用JDBC

spring:
  database:
    url: jdbc:mysql://localhost:3306/ioc_iot
    username: root
    password: 123456
    data:
      url: jdbc:mysql://localhost:3306/jims-his
      username: root
      password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml





