spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    serviceUrl:
      defaultZone: http://mcp:mcp@localhost:1025/eureka
    registry-fetch-interval-seconds: 10
zuul:
  routes:
    mcp-auth:
      path: /auth/**
      serviceId: mcp-auth
